version: "2.1"
services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Etc/UTC
    volumes:
      - prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
volumes:
  prowlarr:
    external: true
networks:
  tarrnet:
    driver: tarrnet
    external: true
