version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Etc/UTC
    volumes:
      - tarrconf:/config
    ports:
      - 9696:9696
    restart: unless-stopped
volumes:
  tarrf:
    external: true
  tarrconf:
    external: true
  tarrdata:
    external: true
networks:
  tarrnet:
    driver: tarrnet
    external: true
