version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:develop
    container_name: radarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Etc/UTC
    volumes:
      - tarrdl:/config
      - tarrdata:/movies
      - tarrf:/tarr-dls
    ports:
      - 7878:7878
    restart: unless-stopped
volumes:
  tarrdl:
    external: true
  tarrf:
    external: true
  tarrconf:
    external: true
  tarrdata:
    external: true
networks:
  tarrnet:
    driver: tarrnet
    external: true
