version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Etc/UTC
    volumes:
      - radarrconf:/config
      - radata:/movies
      - datashare:/torrs
    ports:
      - 7878:7878
    restart: unless-stopped
volumes:
  radarrconf:
    external: true
  radata:
    external: true
  datashare:
    external: true
networks:
  tarrnet:
    driver: tarrnet
    external: true
