---
version: "2.1"
services:
  qbittorrent2:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent2
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Etc/UTC
      - WEBUI_PORT=8081
    volumes:
      - /home/tarr/Downloads:/torrs
      - qbitconf:/newconfig
    networks:
      - tarrnet
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped
volumes:
  datashare:
    external: true
  qbitconf:
    external: true
networks:
  tarrnet:
    driver: tarrnet
    external: true
