---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Etc/UTC
      - WEBUI_PORT=8081
    volumes:
      - tarrf:/tarr-dls
      - tarrconf:/config
        #networks:
        #- tarrnet
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped
volumes:
  tarrf:
    external: true
  tarrconf:
    external: true
  tarrdata:
    external: true
networks:
  tarrnet:
    driver: tarrnet
    external: true
